### ISSUE TITLE
Issues with Windows/MSVC

### ISSUE THREAD

**Issue by heinermann** [jermp/cmd_line_parser#1]
Hello, there are some issues using this with MSVC without language extensions on Windows.

1. `__builtin_unreachable` is undefined. It can be defined as `__assume(0)` or removed.
2. `\e` is a GCC-specific language extension, so help gets printed as `Usage: e[1mbolt-extract.exee[0m [-h,--help] e[4minpute[0m`. `\x1B` works but formatting only works in specific terminals and has the same issue above in the Windows command line (`cmd.exe`).

**Comment by jermp** [comment]
Hi there,
I did not test the code on Windows. The code is meant for Unix systems (Mac and Linux).
But it can certainly be modified to support it. I will look into this but I am not a Windows expert.

**Comment by heinermann** [comment]
No worries just thought I'd share.

**Comment by jermp** [comment]
I removed the bold/underline style (it was not necessary but cool)
and the gcc specific built-in.
Let me know if it now works on Windows too.
Thanks!
